### ISSUE TITLE
Will sync and concurrency objects be added?

### ISSUE THREAD

**Issue by AlexCasual** [DBJDBJ/EASTL2010#1]
I would very much like to see modern concurrency (threads, locks) and executors (https://github.com/chriskohlhoff/executors) elements added to the library =)

**Comment by DBJDBJ** [comment]
Welcome Alex, have you tried EASTL2010 with your kernel code?

Line of thinking is this:

1. EASTL2010 is portable.
1. EASTL2010 we use for the (Win32) "/kernel" projects enjoying standard C++ core language. 
1. We would **not** like to extend EASTL2010, just improve its existing features.  That means no OS-specific code inside.

Many thanks for your involvement ...

**Comment by AlexCasual** [comment]
Yes, I mostly wanted use EASL in kernel driver,
What is the advantage between 2010 and 2020 eastl, if in 2020 you can disable the use of exceptions via macros?

**Comment by DBJDBJ** [comment]
EASTL2010 is simpler smaller and lighter. And still plenty fast when compared to the std lib. Out of the Box. 
EASTL2010 does not use try/throw/catch anywhere. EA_COMPILER_NO_EXCEPTIONS defined or not defined
We compile using CL and the /kernel switch. We simply do not touch EA_COMPILER_NO_EXCEPTIONS .

If you can please use the supplied Visual Studio project.

**Comment by DBJDBJ** [comment]
I can not find the other way to contact you. 

We had a meeting. Never good news :wink:  Basically the outcome is [EASTL2020CORE](https://github.com/DBJDBJ/EASTL2020CORE)

We have decided to face the issues head-on. We are not abandoning the EASTL. We are improving it :smile: 
Please see that readme.

EASTL2010 is in a good shape and ready to be used. No more changes in there. Promise.
